### ISSUE TITLE
Implement CI/CD infrastructure

### ISSUE THREAD

**Issue by stephanosio** [stephanosio/zephyr-qemu#1]
Implement CI/CD infrastructure for building Zephyr QEMU fork based on the GitHub Actions

- [x] #2 Implement Linux build automation
- [x] #3 Implement macOS build automation
- [x] #4 Implement Windows build automation
- [x] Implement release automation

**Comment by stephanosio** [comment]
NOTE: Windows distribution will be cross-compiled from Linux, as we do for `zephyr-crosstool-ng`.

See https://qemu.weilnetz.de/doc/BUILD.txt

**Comment by stephanosio** [comment]
NOTE: The `sdk-ng` build process also includes [building of SeaBIOS](https://github.com/zephyrproject-rtos/sdk-ng/blob/master/meta-zephyr-sdk/recipes-devtools/seabios/zephyr-seabios_1.12.1.bb). Note that this was a sort of "hack" to get custom SeaBIOS without making extensive (and hard-to-maintain) patches to the pulled upstream QEMU. This should no longer be necessary since the QEMU build process already [supports building SeaBIOS](https://github.com/stephanosio/zephyr-qemu/tree/master/roms) and we can maintain such patches here.
